# Starter pipeline
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'hbl-ms-airs-52020'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create --name $(az_rg-network) --location $(az_rg-location)'
